"""add column for updated_at in milage_rate

Revision ID: 18532c4f9a4a
Revises: 4e53a5069593
Create Date: 2026-05-05 23:13:51.578727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18532c4f9a4a'
down_revision: Union[str, Sequence[str], None] = '4e53a5069593'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mileage_rates', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mileage_rates', 'updated_at')
    # ### end Alembic commands ###
