"""add income table with trip relation

Revision ID: 32085ffa8b5c
Revises: b6c5ff95cfe2
Create Date: 2026-04-23 06:58:01.098637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32085ffa8b5c'
down_revision: Union[str, Sequence[str], None] = 'b6c5ff95cfe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'income_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('income_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
