"""user_oauth

Revision ID: 36a9abc9a3b9
Revises: f1946d27b22c
Create Date: 2026-04-13 19:05:10.407191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36a9abc9a3b9'
down_revision: Union[str, Sequence[str], None] = 'f1946d27b22c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_oauth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_user_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id')
    )
    op.create_index(op.f('ix_user_oauth_id'), 'user_oauth', ['id'], unique=False)
    op.create_index(op.f('ix_user_oauth_provider_user_id'), 'user_oauth', ['provider_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_oauth_provider_user_id'), table_name='user_oauth')
    op.drop_index(op.f('ix_user_oauth_id'), table_name='user_oauth')
    op.drop_table('user_oauth')
    # ### end Alembic commands ###
