"""add unique constraints to mileage

Revision ID: 3f8b90115030
Revises: 18532c4f9a4a
Create Date: 2026-05-05 23:18:30.072981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f8b90115030'
down_revision: Union[str, Sequence[str], None] = '18532c4f9a4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_mileage_rate_year', 'mileage_rates', ['year'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_mileage_rate_year', 'mileage_rates', type_='unique')
    # ### end Alembic commands ###
