"""initial

Revision ID: 46deadb266f5
Revises: 
Create Date: 2026-05-04 22:44:57.537126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46deadb266f5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mileage_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rate >= 0', name='ck_rate_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mileage_rates_id'), 'mileage_rates', ['id'], unique=False)
    op.create_index(op.f('ix_mileage_rates_year'), 'mileage_rates', ['year'], unique=False)
    op.create_table('tax_brackets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('filing_status', sa.Enum('single', 'married_filing_jointly', 'married_filing_separately', 'head_of_household', 'qualifying_surviving_spouse', name='filingstatus'), nullable=False),
    sa.Column('min_income', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('max_income', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_income IS NULL OR max_income > min_income', name='ck_income_range_valid'),
    sa.CheckConstraint('min_income >= 0', name='ck_min_income_positive'),
    sa.CheckConstraint('rate >= 0 AND rate <= 1', name='ck_rate_valid'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_brackets_filing_status'), 'tax_brackets', ['filing_status'], unique=False)
    op.create_index(op.f('ix_tax_brackets_id'), 'tax_brackets', ['id'], unique=False)
    op.create_index(op.f('ix_tax_brackets_year'), 'tax_brackets', ['year'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', name='user_role_enum'), server_default=sa.text("'user'"), nullable=False),
    sa.Column('filing_status', sa.Enum('single', 'married_filing_jointly', 'married_filing_separately', 'head_of_household', 'qualifying_surviving_spouse', name='filingstatus'), server_default=sa.text("'single'"), nullable=True),
    sa.Column('email_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('category', sa.Enum('FOOD', 'TRANSPORT', 'VEHICLE', 'SUPPLIES', 'SOFTWARE', 'PHONE', 'INTERNET', 'MARKETING', 'EDUCATION', 'RENT', 'UTILITIES', 'OTHER', name='expense_category_enum'), nullable=False),
    sa.Column('incurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('receipt_url', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='check_amount_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    op.create_index(op.f('ix_expenses_incurred_at'), 'expenses', ['incurred_at'], unique=False)
    op.create_index(op.f('ix_expenses_user_id'), 'expenses', ['user_id'], unique=False)
    op.create_index('ix_expenses_user_id_incurred_at', 'expenses', ['user_id', 'incurred_at'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_index(op.f('ix_sessions_refresh_token'), 'sessions', ['refresh_token'], unique=True)
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('start_lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('start_lng', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('end_lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('end_lng', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('start_address', sa.String(length=100), nullable=False),
    sa.Column('end_address', sa.String(length=100), nullable=False),
    sa.Column('distance_miles', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('platform', sa.Enum('UBER_EATS', 'SPARK', 'DOORDASH', 'LYFT', 'UBER', 'GRUBHUB', 'INSTACART', 'AMAZON_FLEX', 'SHIPT', 'OTHER', name='trip_platform'), nullable=False),
    sa.Column('category', sa.Enum('BUSINESS', 'PERSONAL', name='trip_category'), nullable=False),
    sa.Column('deduction_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'start_time', 'end_time')
    )
    op.create_index(op.f('ix_trips_id'), 'trips', ['id'], unique=False)
    op.create_table('user_2fa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('secret', sa.Text(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_2fa_id'), 'user_2fa', ['id'], unique=False)
    op.create_table('user_oauth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_user_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id')
    )
    op.create_index(op.f('ix_user_oauth_id'), 'user_oauth', ['id'], unique=False)
    op.create_index(op.f('ix_user_oauth_provider_user_id'), 'user_oauth', ['provider_user_id'], unique=False)
    op.create_table('income',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('source', sa.Enum('GIG_PLATFORM', 'BUSINESS', 'EMPLOYMENT', 'PASSIVE', 'OTHER', name='incometype'), nullable=False),
    sa.Column('platform', sa.Enum('UBER_EATS', 'SPARK', 'DOORDASH', 'LYFT', 'UBER', 'GRUBHUB', 'INSTACART', 'AMAZON_FLEX', 'SHIPT', 'OTHER', name='tripplatform'), nullable=True),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('business_name', sa.String(length=255), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_income_id'), 'income', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_income_id'), table_name='income')
    op.drop_table('income')
    op.drop_index(op.f('ix_user_oauth_provider_user_id'), table_name='user_oauth')
    op.drop_index(op.f('ix_user_oauth_id'), table_name='user_oauth')
    op.drop_table('user_oauth')
    op.drop_index(op.f('ix_user_2fa_id'), table_name='user_2fa')
    op.drop_table('user_2fa')
    op.drop_index(op.f('ix_trips_id'), table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_sessions_refresh_token'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_expenses_user_id_incurred_at', table_name='expenses')
    op.drop_index(op.f('ix_expenses_user_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_incurred_at'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tax_brackets_year'), table_name='tax_brackets')
    op.drop_index(op.f('ix_tax_brackets_id'), table_name='tax_brackets')
    op.drop_index(op.f('ix_tax_brackets_filing_status'), table_name='tax_brackets')
    op.drop_table('tax_brackets')
    op.drop_index(op.f('ix_mileage_rates_year'), table_name='mileage_rates')
    op.drop_index(op.f('ix_mileage_rates_id'), table_name='mileage_rates')
    op.drop_table('mileage_rates')
    # ### end Alembic commands ###
