"""add expenses table with constraints and indexes

Revision ID: 81cdd4038eca
Revises: 72023d1b4ffd
Create Date: 2026-04-27 23:25:20.090407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81cdd4038eca'
down_revision: Union[str, Sequence[str], None] = '72023d1b4ffd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('category', sa.Enum('FOOD', 'TRANSPORT', 'VEHICLE', 'SUPPLIES', 'SOFTWARE', 'PHONE', 'INTERNET', 'MARKETING', 'EDUCATION', 'RENT', 'UTILITIES', 'OTHER', name='expense_category_enum'), nullable=False),
    sa.Column('incurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('receipt_url', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='check_amount_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    op.create_index(op.f('ix_expenses_incurred_at'), 'expenses', ['incurred_at'], unique=False)
    op.create_index(op.f('ix_expenses_user_id'), 'expenses', ['user_id'], unique=False)
    op.create_index('ix_expenses_user_id_incurred_at', 'expenses', ['user_id', 'incurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_expenses_user_id_incurred_at', table_name='expenses')
    op.drop_index(op.f('ix_expenses_user_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_incurred_at'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.drop_table('expenses')
    # ### end Alembic commands ###
