"""add trips table

Revision ID: 88d21ae96e31
Revises: 36a9abc9a3b9
Create Date: 2026-04-14 07:03:55.197774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88d21ae96e31'
down_revision: Union[str, Sequence[str], None] = '36a9abc9a3b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('start_lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('start_lng', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('end_lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('end_lng', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('start_address', sa.String(length=100), nullable=False),
    sa.Column('end_address', sa.String(length=100), nullable=False),
    sa.Column('platform', sa.Enum('UBER_EATS', 'SPARK', 'DOORDASH', 'LYFT', 'UBER', 'GRUBHUB', 'INSTACART', 'AMAZON_FLEX', 'SHIPT', 'OTHER', name='trip_platform'), nullable=False),
    sa.Column('category', sa.Enum('BUSINESS', 'PERSONAL', name='trip_category'), nullable=False),
    sa.Column('deduction_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'start_time', 'end_time')
    )
    op.create_index(op.f('ix_trips_id'), 'trips', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trips_id'), table_name='trips')
    op.drop_table('trips')
    # ### end Alembic commands ###
