"""added income_amount

Revision ID: b6c5ff95cfe2
Revises: 2af1acb4f337
Create Date: 2026-04-20 17:46:11.733520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6c5ff95cfe2'
down_revision: Union[str, Sequence[str], None] = '2af1acb4f337'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('income_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'income_amount')
    # ### end Alembic commands ###
