"""remove unique constraint on income

Revision ID: be8572335743
Revises: c87c2e70890e
Create Date: 2026-04-27 17:14:13.638609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be8572335743'
down_revision: Union[str, Sequence[str], None] = 'c87c2e70890e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('income_user_id_received_at_key'), 'income', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('income_user_id_received_at_key'), 'income', ['user_id', 'received_at'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
