"""add income table with trip relation

Revision ID: c87c2e70890e
Revises: 32085ffa8b5c
Create Date: 2026-04-23 06:59:07.638370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c87c2e70890e'
down_revision: Union[str, Sequence[str], None] = '32085ffa8b5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('income',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('source', sa.Enum('GIG_PLATFORM', 'BUSINESS', 'EMPLOYMENT', 'PASSIVE', 'OTHER', name='incometype'), nullable=False),
    sa.Column('platform', sa.Enum('UBER_EATS', 'SPARK', 'DOORDASH', 'LYFT', 'UBER', 'GRUBHUB', 'INSTACART', 'AMAZON_FLEX', 'SHIPT', 'OTHER', name='tripplatform'), nullable=True),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('business_name', sa.String(length=255), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'received_at')
    )
    op.create_index(op.f('ix_income_id'), 'income', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_income_id'), table_name='income')
    op.drop_table('income')
    # ### end Alembic commands ###
